//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voiture()
        {
            this.reservations = new HashSet<reservation>();
            this.contrats = new HashSet<contrat>();
        }
    
        public int idcar { get; set; }
        public Nullable<int> idcat { get; set; }
        public Nullable<int> idmodele { get; set; }
        public string immat { get; set; }
        public string carte_grise { get; set; }
        public Nullable<int> nbporte { get; set; }
        public Nullable<int> nbplace { get; set; }
        public Nullable<int> puissance { get; set; }
        public Nullable<System.DateTime> date_aquis { get; set; }
        public Nullable<System.DateTime> datedebut_assurance { get; set; }
        public Nullable<System.DateTime> datefin_assurance { get; set; }
        public Nullable<decimal> cout_assurance { get; set; }
        public string typecarburant { get; set; }
        public Nullable<decimal> prixJour { get; set; }
    
        public virtual category category { get; set; }
        public virtual modele modele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contrat> contrats { get; set; }
    }
}
